class Constants:
    UNSAVED_WINDOW_TITLE = "(Unsaved Document)"
    SAVED_FILE_EXTENSION = ".ewho3"
    RESET_FONT_SIZE = 12
    MAIN_TITLE_LABEL_PREFIX = "MainTitle_"
    SUBTITLE_LABEL_PREFIX = "Subtitle_"
    MAIN_TITLE_FONT_SIZE_INCREMENT = 6
    SUBTITLE_FONT_SIZE_INCREMENT = 3
    SESSION_CONSOLE_INDENTATION_DEPTH = 3
